### ISSUE TITLE
[Refactor] (windows-installer) get the .exe file from the assets of the latest release

### ISSUE THREAD

**Issue by EusebioSimango** [obadiaspelembe/samora-lang-installers#4]
The samora-lang's official repository already provide built binaries for windows on: [https://github.com/GraHms/Samora-Lang/releases/latest](https://github.com/GraHms/Samora-Lang/releases/latest), and there's no need to install `go` and to build the binaries on the installer, now it's  just a matter of download, extract and move to the right directory.

#### Resouces that may help:
- [JSON containing information about the latest release, including the url to the windows binary](https://api.github.com/repos/Grahms/Samora-Lang/releases/latest)

**Comment by obadiaspelembe** [comment]
Hi @EusebioSimango  that's perfect, will work on refactoring this to the new approach, thanks for sharing.

Look forward updates.

Cheers

**Comment by obadiaspelembe** [comment]
Hi @EusebioSimango ,
Thanks for this issue, it's fixed under https://github.com/obadiaspelembe/samora-lang-installers/pull/5
